name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      # - name: Set npm registry
      #   run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
      - name: Install deps and build (with cache)
        run: yarn install
      - run: yarn semantic-release
        env:
          NPM_TOKEN: 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
          GITHUB_TOKEN: ${GH_TOKEN}
